CREATE TABLE `prezenta` (
  `ID_PREZENTA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_MATERIE` int(11) NOT NULL,
  `DATA` date NOT NULL,
  `TIP_PREZENTA` varchar(45) CHARACTER SET dec8 NOT NULL,
  PRIMARY KEY (`ID_PREZENTA`)
)

CREATE TABLE `prezenta_user` (
  `ID_PREZENTA_USER` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PREZENTA` int(11) NOT NULL,
  `ID_USER` int(11) NOT NULL,
  PRIMARY KEY (`ID_PREZENTA_USER`)
) 